# -*- coding: utf-8 -*-
"""Car Crawling

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vdkFPzqh9FlswbFERMWp-wtina5jg9ek
"""

import requests
import re
import pandas as pd
import urllib.request
import os
import time
from random import randint
from IPython.display import clear_output

image_storage = '/content/drive/MyDrive/car crawling'

url = 'https://www.mobil123.com/mobil-dijual/indonesia?type=used&page_number={}&page_size=25'
headers = {'User-Agent': 'Mozilla/5.0 (X11; OpenBSD i386) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36'}

for i in range(108,2246) :
  print(url.format(str(i)))
  resp = requests.request('GET', url.format(str(i)), headers=headers)
  regex_list = '<header.*?<a class="listing__overlay.*?href="(.*?)"'
  reobj = re.compile(regex_list, re.DOTALL)
  list_url = reobj.findall(resp.text)

  filenames = []
  brands = []
  models = []
  years = []
  colors = []
  urls = []

  for link in list_url :
    try :
      print('Requesting: ', link)
      tic = time.perf_counter()
      content_resp = requests.request('GET', link, headers=headers)
      id = link.split('/')[-1]

      # merek
      regex_merek = 'car-front.*?<span class="float--right" itemprop="manufacturer">(.*?)</span>'
      reobj = re.compile(regex_merek, re.DOTALL)
      merek = reobj.findall(content_resp.text)[0]

      # model
      regex_model = 'two-cars.*?<span class="float--right" itemprop="model">(.*?)</span>'
      reobj = re.compile(regex_model, re.DOTALL)
      model = reobj.findall(content_resp.text)[0]

      # tahun
      regex_tahun = 'calendar.*?<span class="float--right">(.*?)</span>'
      reobj = re.compile(regex_tahun, re.DOTALL)
      tahun = reobj.findall(content_resp.text)[0]

      # warna
      regex_warna = 'paint.*?<span class="float--right">(.*?)</span>'
      reobj = re.compile(regex_warna, re.DOTALL)
      warna = reobj.findall(content_resp.text)[0]

      # photos
      regex_foto = "background-image:.*?url\('(.*?)'\)"
      reobj = re.compile(regex_foto, re.DOTALL)
      photos = reobj.findall(content_resp.text)

      i = 1
      for photo in photos :
        photo = photo.replace('thumb-l', 'gallery')
        filename = id + '_' + str(i) + '.jpg'
        urllib.request.urlretrieve(photo, os.path.join(image_storage, filename))
        filenames.append(filename)
        urls.append(photo)
        brands.append(merek)
        models.append(model)
        colors.append(warna)
        years.append(tahun)
        i += 1
      toc = time.perf_counter()
      print('Finished in: ' + str(toc-tic) + ' s')

    except Exception as error:
      print(error)

  data = pd.DataFrame(list(zip(filenames,brands,models,years,colors,urls)), columns=['filename','brand','model','tahun','warna','image_url'])
  data.to_csv('/content/drive/MyDrive/car crawling/dataset_label.csv', header=None, mode='a')
  clear_output(wait=True)
  time.sleep(randint(2,4))

# Create database frame
data = pd.DataFrame(list(zip([],[],[],[],[],[])), columns=['filename','brand','model','tahun','warna','image_url'])
data.to_csv('/content/drive/MyDrive/car crawling/dataset_label.csv')

!rm -r '/content/drive/MyDrive/car crawling/'

ids = []
for elem in data[1][1:]:
  id = reobj.findall(elem)[0]
  if id not in ids :
    ids.append(id)

import glob

data = glob.glob('/content/drive/MyDrive/car crawling/*.jpg')

len(data)

ids = []
reobj = re.compile('([0-9]*)_')
for elem in data:
  elem = elem.split('/')[-1]
  id = reobj.findall(elem)[0]
  if id not in ids :
    ids.append(id)
  else :
    pass

len(ids)

data = pd.read_csv('/content/drive/MyDrive/car crawling/dataset_label.csv',header=None)

data[data[1]=='4989401_13.jpg']
